/**
 * PROVIDER VERIFICATION — reg-reporting side of the trade↔reg-reporting
 * contract. Replays the pact generated by trade's consumer test against the
 * REAL app (fresh in-memory store per run ⇒ the "empty store" state).
 */
import { Verifier } from '@pact-foundation/pact';
import { afterAll, beforeAll, describe, it } from 'vitest';
import { buildApp } from '../../src/app.js';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dirname_ = path.dirname(fileURLToPath(import.meta.url));
const PORT = 3904;

describe('reg-reporting honours the pact published by trade', () => {
  const app = buildApp();

  beforeAll(async () => {
    await app.listen({ port: PORT, host: '127.0.0.1' });
  });

  afterAll(async () => {
    await app.close();
  });

  it('verifies all interactions', async () => {
    const verifier = new Verifier({
      provider: 'reg-reporting',
      providerBaseUrl: `http://127.0.0.1:${PORT}`,
      pactUrls: [path.resolve(dirname_, '../../../../pacts/trade-reg-reporting.json')],
      stateHandlers: {
        'the reporting store is empty': async () => {
          /* a fresh buildApp() store is empty — nothing to do */
          return 'empty';
        },
      },
    });
    await verifier.verifyProvider();
  }, 60_000);
});
