/**
 * PROVIDER VERIFICATION — market-data side of the trade↔market-data contract.
 * Replays the pact generated by trade's consumer test against the REAL app.
 * File-based here for zero-infra CI; swap pactUrls for a broker URL + token
 * in a multi-repo estate (see docs/STANDARDS.md §4).
 */
import { Verifier } from '@pact-foundation/pact';
import { afterAll, beforeAll, describe, it } from 'vitest';
import { buildApp } from '../../src/app.js';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dirname_ = path.dirname(fileURLToPath(import.meta.url));
const PORT = 3901;

describe('market-data honours the pact published by trade', () => {
  const app = buildApp();

  beforeAll(async () => {
    await app.listen({ port: PORT, host: '127.0.0.1' });
  });

  afterAll(async () => {
    await app.close();
  });

  it('verifies all interactions', async () => {
    const verifier = new Verifier({
      provider: 'market-data',
      providerBaseUrl: `http://127.0.0.1:${PORT}`,
      pactUrls: [path.resolve(dirname_, '../../../../pacts/trade-market-data.json')],
      stateHandlers: {
        'a quote exists for AAPL': async () => {
          /* StaticPriceSource already seeds AAPL — nothing to do */
          return 'seeded';
        },
      },
    });
    await verifier.verifyProvider();
  }, 60_000);
});
